version: "3"

services:
    php:
        build:
          context: ./DockerSetup/php
          dockerfile: Dockerfile
        container_name: php-container
        volumes:
          - ./public:/var/www/html
        restart: always

    nginx:
        image: nginx:alpine
        container_name: nginx-container
        restart: always
        links:
          - php
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - ./public:/var/www/html
          - ./service/nginx/default.conf:/etc/nginx/conf.d/default.conf
          
volumes:
    php:
